-- Migration 004: Fix timestamp defaults for clock consistency
-- This migration adds DEFAULT NOW() to start_time columns to ensure
-- all timestamps are generated by the database server, not the app server.
-- This fixes the clock drift issue causing negative elapsed_time values.

-- Add DEFAULT NOW() to time_entry.start_time
ALTER TABLE public.time_entry 
ALTER COLUMN start_time SET DEFAULT NOW();

-- Add DEFAULT NOW() to timer_session.start_time
ALTER TABLE public.timer_session 
ALTER COLUMN start_time SET DEFAULT NOW();

-- Add DEFAULT NOW() to timer_segment.start_time  
ALTER TABLE public.timer_segment 
ALTER COLUMN start_time SET DEFAULT NOW();

-- Note: After applying this migration, the app code should NOT pass
-- start_time values from JavaScript. Let the database generate them
-- using the DEFAULT NOW() to ensure timestamp consistency.